# Generated by Django 5.0.6 on 2024-07-05 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("oauth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="verifier",
            name="profile_photo",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="divar_post_id",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="seller",
            name="rate",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="user",
            name="oauth",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="oauth.oauth",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
