# Generated by Django 5.0.6 on 2024-07-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='rate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
