# Generated by Django 5.0.6 on 2024-07-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_seller_rate_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='divar_post_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
