# Generated by Django 5.0.6 on 2024-07-04 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_post_divar_post_id'),
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='oauth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oauth.oauth'),
        ),
    ]
