# Generated by Django 5.0.6 on 2024-07-05 06:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_verifier_profile_photo_alter_post_divar_post_id_and_more"),
        ("accounts", "0004_alter_user_oauth"),
    ]

    operations = []
