# Generated by Django 5.0.6 on 2024-07-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationrequest',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Buyer Claimed'), (2, 'Seller Approved'), (3, 'Seller Rejected')], default=1),
        ),
    ]
