# Generated by Django 5.0.6 on 2024-07-05 06:23

import survey.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="uuid",
            field=models.CharField(
                default=survey.models.generate_short_uuid,
                editable=False,
                max_length=12,
                unique=True,
            ),
        ),
    ]
